version: "3.3"
services:
  mysql-db:
    image: mysql:8.0.1
    container_name: mysql-db
    environment: 
       MYSQL_ROOT_PASSWORD: "123"
       TZ: America/Manaus
    ports:
       - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  phpmyadmin-db:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-db
    ports:
       - 8079:80
    links: 
      - mysql-db:db
  php7.3:
    image: cbcarlos7/php73
    container_name: php7.3
    volumes:
      - ./backend:/var/www/html
    ports:
      - 81:8080   
  server:
    image: cbcarlos7/php73
    container_name: server
    volumes:
      - ./www:/var/www/html
    ports:
      - 80:8080 
networks:
  default:
    external:
      name: mysql-network      
   
    

     

